const seedRestaurantData = [
  {
    name: "Campus Pizza",
    address: "160 University Ave W #2, Waterloo, ON N2L 3E9",
    type: "Pizzeria",
    budget: "LOW",
    description: "giant slices, affordable prices",
    rating: 2,
    numRatings: 1,
  },
  {
    name: "Shawerma Plus",
    address: "160 University Ave W, Waterloo, ON N2L 3E9",
    type: "Middle Eastern",
    budget: "MEDIUM",
    description: "better than Lazeez apparently",
    rating: 4,
    numRatings: 1,
  },
  {
    name: "Mr Panino's Beijing House",
    address: "106 University Ave W #1, Waterloo, ON N2L 3E9",
    type: "Chinese",
    budget: "LOW",
    description: "good portions, questionable health inspection records though 🤔",
    rating: 2,
    numRatings: 1,
  },
  {
    name: "Foodie Fruitie",
    address: "203 Lester St #7, Waterloo, ON N2L 0B5",
    type: "East Asian",
    budget: "LOW",
    description: "good selection on the menu, sushi, ramen, curry, etc.",
    rating: 4,
    numRatings: 1,
  },
  {
    name: "CoCo",
    address: "203 Lester St #3, Waterloo, ON N2L 3W4",
    type: "Bubble Tea",
    budget: "LOW",
    description: "relatively cheap bubble tea",
    rating: 3,
    numRatings: 1,
  },
  {
    name: "Sharetea",
    address: "256 Phillip St d, Waterloo, ON N2L 3W8",
    type: "Bubble Tea",
    budget: "MEDIUM",
    description: "more expensive bubble tea",
    rating: 3,
    numRatings: 1,
  },
  {
    name: "Williams Fresh Cafe",
    address: "170 University Ave W, Waterloo, ON N2L 3E9",
    type: "Coffee",
    budget: "MEDIUM",
    description: "good study spot",
    rating: 3,
    numRatings: 1,
  },
  {
    name: "O'My Bakery",
    address: "262-264 Phillip St, Waterloo, ON N2L 3W8",
    type: "Bakery",
    budget: "LOW",
    description: "good for grabbing a quick bite",
    rating: 3,
    numRatings: 1,
  },
  {
    name: "The Poke Box",
    address: "255 King St N #3, Waterloo, ON N2J 4V2",
    type: "Poke",
    budget: "MEDIUM",
    description: "good stuff!",
    rating: 4,
    numRatings: 1,
  },
  {
    name: "Bao Sandwich Bar",
    address: "62 Balsam St B106, Waterloo, ON N2L 3H2",
    type: "East Asian",
    budget: "LOW",
    description: "good food but hard to get a seat",
    rating: 4,
    numRatings: 1,
  },
  {
    name: "Tim Horton's",
    address: "151 Columbia St W, Waterloo, ON N2L 3L2",
    type: "Coffee",
    budget: "LOW",
    description: "typical Tim Horton's, short walk if you live at icon",
    rating: 3,
    numRatings: 1,
  },
];

const seedRestaurantGroupData =[{
    name: "Best Pizza Place",
    description: "Only Campus Pizza",
    restaurantIds: [1],
  },
  {
    name: "Boba Places",
    description: "fun boba places",
    restaurantIds: [5,6],
  },];
export {seedRestaurantGroupData,seedRestaurantData};


